import { Employee, Department } from '@/types/employee';

// Departments
export const departments: Department[] = [
  { id: 'it', name: 'Information Technology', nameAr: 'تقنية المعلومات', employeeCount: 8 },
  { id: 'hr', name: 'Human Resources', nameAr: 'الموارد البشرية', employeeCount: 4 },
  { id: 'finance', name: 'Finance', nameAr: 'المالية', employeeCount: 5 },
  { id: 'operations', name: 'Operations', nameAr: 'العمليات', employeeCount: 6 },
  { id: 'sales', name: 'Sales & Marketing', nameAr: 'المبيعات والتسويق', employeeCount: 5 },
  { id: 'legal', name: 'Legal', nameAr: 'الشؤون القانونية', employeeCount: 2 },
];

// Mock employees data (30 employees)
export const mockEmployees: Employee[] = [
  // IT Department
  {
    id: 'emp-001',
    employeeNumber: 'EMP-2024-0001',
    name: 'Ahmed Mohammed Al-Saeed',
    nameAr: 'أحمد محمد السعيد',
    email: 'ahmed.alsaeed@company.com',
    phone: '+966 50 123 4567',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ahmed',
    position: 'Chief Technology Officer',
    positionAr: 'المدير التنفيذي للتقنية',
    department: 'Information Technology',
    departmentAr: 'تقنية المعلومات',
    joinDate: '2020-01-15',
    employmentStatus: 'active',
    location: 'Riyadh',
    locationAr: 'الرياض',
  },
  {
    id: 'emp-002',
    employeeNumber: 'EMP-2024-0002',
    name: 'Mohammed Ahmed Al-Omari',
    nameAr: 'محمد أحمد العمري',
    email: 'm.alomari@company.com',
    phone: '+966 50 234 5678',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mohammed',
    position: 'Senior Software Developer',
    positionAr: 'مطور برمجيات أول',
    department: 'Information Technology',
    departmentAr: 'تقنية المعلومات',
    managerId: 'emp-001',
    managerName: 'Ahmed Mohammed Al-Saeed',
    managerNameAr: 'أحمد محمد السعيد',
    joinDate: '2021-03-20',
    employmentStatus: 'active',
    location: 'Riyadh',
    locationAr: 'الرياض',
  },
  {
    id: 'emp-003',
    employeeNumber: 'EMP-2024-0003',
    name: 'Fahad Abdullah Al-Qahtani',
    nameAr: 'فهد عبدالله القحطاني',
    email: 'f.alqahtani@company.com',
    phone: '+966 50 345 6789',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fahad',
    position: 'DevOps Engineer',
    positionAr: 'مهندس DevOps',
    department: 'Information Technology',
    departmentAr: 'تقنية المعلومات',
    managerId: 'emp-001',
    managerName: 'Ahmed Mohammed Al-Saeed',
    managerNameAr: 'أحمد محمد السعيد',
    joinDate: '2021-06-10',
    employmentStatus: 'active',
    location: 'Riyadh',
    locationAr: 'الرياض',
  },
  {
    id: 'emp-004',
    employeeNumber: 'EMP-2024-0004',
    name: 'Khalid Hassan Al-Mutairi',
    nameAr: 'خالد حسن المطيري',
    email: 'k.almutairi@company.com',
    phone: '+966 50 456 7890',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Khalid',
    position: 'Frontend Developer',
    positionAr: 'مطور واجهات أمامية',
    department: 'Information Technology',
    departmentAr: 'تقنية المعلومات',
    managerId: 'emp-001',
    managerName: 'Ahmed Mohammed Al-Saeed',
    managerNameAr: 'أحمد محمد السعيد',
    joinDate: '2022-02-14',
    employmentStatus: 'active',
    location: 'Jeddah',
    locationAr: 'جدة',
  },
  {
    id: 'emp-005',
    employeeNumber: 'EMP-2024-0005',
    name: 'Omar Saleh Al-Zahrani',
    nameAr: 'عمر صالح الزهراني',
    email: 'o.alzahrani@company.com',
    phone: '+966 50 567 8901',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Omar',
    position: 'Backend Developer',
    positionAr: 'مطور خلفي',
    department: 'Information Technology',
    departmentAr: 'تقنية المعلومات',
    managerId: 'emp-001',
    managerName: 'Ahmed Mohammed Al-Saeed',
    managerNameAr: 'أحمد محمد السعيد',
    joinDate: '2022-05-01',
    employmentStatus: 'active',
    location: 'Riyadh',
    locationAr: 'الرياض',
  },
  {
    id: 'emp-006',
    employeeNumber: 'EMP-2024-0006',
    name: 'Saud Ali Al-Ghamdi',
    nameAr: 'سعود علي الغامدي',
    email: 's.alghamdi@company.com',
    phone: '+966 50 678 9012',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Saud',
    position: 'UX/UI Designer',
    positionAr: 'مصمم تجربة مستخدم',
    department: 'Information Technology',
    departmentAr: 'تقنية المعلومات',
    managerId: 'emp-001',
    managerName: 'Ahmed Mohammed Al-Saeed',
    managerNameAr: 'أحمد محمد السعيد',
    joinDate: '2022-08-15',
    employmentStatus: 'active',
    location: 'Riyadh',
    locationAr: 'الرياض',
  },
  {
    id: 'emp-007',
    employeeNumber: 'EMP-2024-0007',
    name: 'Faisal Ibrahim Al-Shammari',
    nameAr: 'فيصل إبراهيم الشمري',
    email: 'f.alshammari@company.com',
    phone: '+966 50 789 0123',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Faisal',
    position: 'QA Engineer',
    positionAr: 'مهندس ضمان جودة',
    department: 'Information Technology',
    departmentAr: 'تقنية المعلومات',
    managerId: 'emp-001',
    managerName: 'Ahmed Mohammed Al-Saeed',
    managerNameAr: 'أحمد محمد السعيد',
    joinDate: '2023-01-10',
    employmentStatus: 'active',
    location: 'Dammam',
    locationAr: 'الدمام',
  },
  {
    id: 'emp-008',
    employeeNumber: 'EMP-2024-0008',
    name: 'Turki Mohammed Al-Dosari',
    nameAr: 'تركي محمد الدوسري',
    email: 't.aldosari@company.com',
    phone: '+966 50 890 1234',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Turki',
    position: 'Data Analyst',
    positionAr: 'محلل بيانات',
    department: 'Information Technology',
    departmentAr: 'تقنية المعلومات',
    managerId: 'emp-001',
    managerName: 'Ahmed Mohammed Al-Saeed',
    managerNameAr: 'أحمد محمد السعيد',
    joinDate: '2023-04-01',
    employmentStatus: 'active',
    location: 'Riyadh',
    locationAr: 'الرياض',
  },

  // HR Department
  {
    id: 'emp-009',
    employeeNumber: 'EMP-2024-0009',
    name: 'Noura Khalid Al-Harbi',
    nameAr: 'نورة خالد الحربي',
    email: 'n.alharbi@company.com',
    phone: '+966 50 901 2345',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Noura',
    position: 'HR Director',
    positionAr: 'مديرة الموارد البشرية',
    department: 'Human Resources',
    departmentAr: 'الموارد البشرية',
    joinDate: '2020-03-01',
    employmentStatus: 'active',
    location: 'Riyadh',
    locationAr: 'الرياض',
  },
  {
    id: 'emp-010',
    employeeNumber: 'EMP-2024-0010',
    name: 'Sarah Ahmed Al-Malki',
    nameAr: 'سارة أحمد المالكي',
    email: 's.almalki@company.com',
    phone: '+966 50 012 3456',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    position: 'Recruitment Specialist',
    positionAr: 'أخصائية توظيف',
    department: 'Human Resources',
    departmentAr: 'الموارد البشرية',
    managerId: 'emp-009',
    managerName: 'Noura Khalid Al-Harbi',
    managerNameAr: 'نورة خالد الحربي',
    joinDate: '2021-07-15',
    employmentStatus: 'active',
    location: 'Riyadh',
    locationAr: 'الرياض',
  },
  {
    id: 'emp-011',
    employeeNumber: 'EMP-2024-0011',
    name: 'Huda Mohammed Al-Otaibi',
    nameAr: 'هدى محمد العتيبي',
    email: 'h.alotaibi@company.com',
    phone: '+966 50 123 4567',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Huda',
    position: 'HR Coordinator',
    positionAr: 'منسقة موارد بشرية',
    department: 'Human Resources',
    departmentAr: 'الموارد البشرية',
    managerId: 'emp-009',
    managerName: 'Noura Khalid Al-Harbi',
    managerNameAr: 'نورة خالد الحربي',
    joinDate: '2022-09-01',
    employmentStatus: 'active',
    location: 'Riyadh',
    locationAr: 'الرياض',
  },
  {
    id: 'emp-012',
    employeeNumber: 'EMP-2024-0012',
    name: 'Maha Abdullah Al-Shahrani',
    nameAr: 'مها عبدالله الشهراني',
    email: 'm.alshahrani@company.com',
    phone: '+966 50 234 5678',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maha',
    position: 'Training & Development Officer',
    positionAr: 'مسؤولة تدريب وتطوير',
    department: 'Human Resources',
    departmentAr: 'الموارد البشرية',
    managerId: 'emp-009',
    managerName: 'Noura Khalid Al-Harbi',
    managerNameAr: 'نورة خالد الحربي',
    joinDate: '2023-02-20',
    employmentStatus: 'active',
    location: 'Jeddah',
    locationAr: 'جدة',
  },

  // Finance Department
  {
    id: 'emp-013',
    employeeNumber: 'EMP-2024-0013',
    name: 'Abdullah Nasser Al-Dawsari',
    nameAr: 'عبدالله ناصر الدوسري',
    email: 'a.aldawsari@company.com',
    phone: '+966 50 345 6789',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Abdullah',
    position: 'Finance Manager',
    positionAr: 'مدير مالي',
    department: 'Finance',
    departmentAr: 'المالية',
    joinDate: '2020-05-01',
    employmentStatus: 'active',
    location: 'Riyadh',
    locationAr: 'الرياض',
  },
  {
    id: 'emp-014',
    employeeNumber: 'EMP-2024-0014',
    name: 'Yasser Fahad Al-Anazi',
    nameAr: 'ياسر فهد العنزي',
    email: 'y.alanazi@company.com',
    phone: '+966 50 456 7890',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Yasser',
    position: 'Senior Accountant',
    positionAr: 'محاسب أول',
    department: 'Finance',
    departmentAr: 'المالية',
    managerId: 'emp-013',
    managerName: 'Abdullah Nasser Al-Dawsari',
    managerNameAr: 'عبدالله ناصر الدوسري',
    joinDate: '2021-04-15',
    employmentStatus: 'active',
    location: 'Riyadh',
    locationAr: 'الرياض',
  },
  {
    id: 'emp-015',
    employeeNumber: 'EMP-2024-0015',
    name: 'Reem Saleh Al-Otaibi',
    nameAr: 'ريم صالح العتيبي',
    email: 'r.alotaibi@company.com',
    phone: '+966 50 567 8901',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Reem',
    position: 'Financial Analyst',
    positionAr: 'محللة مالية',
    department: 'Finance',
    departmentAr: 'المالية',
    managerId: 'emp-013',
    managerName: 'Abdullah Nasser Al-Dawsari',
    managerNameAr: 'عبدالله ناصر الدوسري',
    joinDate: '2022-01-10',
    employmentStatus: 'active',
    location: 'Riyadh',
    locationAr: 'الرياض',
  },
  {
    id: 'emp-016',
    employeeNumber: 'EMP-2024-0016',
    name: 'Bandar Ali Al-Shehri',
    nameAr: 'بندر علي الشهري',
    email: 'b.alshehri@company.com',
    phone: '+966 50 678 9012',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bandar',
    position: 'Accountant',
    positionAr: 'محاسب',
    department: 'Finance',
    departmentAr: 'المالية',
    managerId: 'emp-013',
    managerName: 'Abdullah Nasser Al-Dawsari',
    managerNameAr: 'عبدالله ناصر الدوسري',
    joinDate: '2022-06-01',
    employmentStatus: 'active',
    location: 'Jeddah',
    locationAr: 'جدة',
  },
  {
    id: 'emp-017',
    employeeNumber: 'EMP-2024-0017',
    name: 'Lama Mohammed Al-Qarni',
    nameAr: 'لمى محمد القرني',
    email: 'l.alqarni@company.com',
    phone: '+966 50 789 0123',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lama',
    position: 'Payroll Specialist',
    positionAr: 'أخصائية رواتب',
    department: 'Finance',
    departmentAr: 'المالية',
    managerId: 'emp-013',
    managerName: 'Abdullah Nasser Al-Dawsari',
    managerNameAr: 'عبدالله ناصر الدوسري',
    joinDate: '2023-03-15',
    employmentStatus: 'active',
    location: 'Riyadh',
    locationAr: 'الرياض',
  },

  // Operations Department
  {
    id: 'emp-018',
    employeeNumber: 'EMP-2024-0018',
    name: 'Majed Khalid Al-Juhani',
    nameAr: 'ماجد خالد الجهني',
    email: 'm.aljuhani@company.com',
    phone: '+966 50 890 1234',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Majed',
    position: 'Operations Manager',
    positionAr: 'مدير عمليات',
    department: 'Operations',
    departmentAr: 'العمليات',
    joinDate: '2020-07-01',
    employmentStatus: 'active',
    location: 'Riyadh',
    locationAr: 'الرياض',
  },
  {
    id: 'emp-019',
    employeeNumber: 'EMP-2024-0019',
    name: 'Waleed Hassan Al-Harthi',
    nameAr: 'وليد حسن الحارثي',
    email: 'w.alharthi@company.com',
    phone: '+966 50 901 2345',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Waleed',
    position: 'Operations Supervisor',
    positionAr: 'مشرف عمليات',
    department: 'Operations',
    departmentAr: 'العمليات',
    managerId: 'emp-018',
    managerName: 'Majed Khalid Al-Juhani',
    managerNameAr: 'ماجد خالد الجهني',
    joinDate: '2021-05-10',
    employmentStatus: 'active',
    location: 'Riyadh',
    locationAr: 'الرياض',
  },
  {
    id: 'emp-020',
    employeeNumber: 'EMP-2024-0020',
    name: 'Talal Ibrahim Al-Subaie',
    nameAr: 'طلال إبراهيم السبيعي',
    email: 't.alsubaie@company.com',
    phone: '+966 50 012 3456',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Talal',
    position: 'Operations Coordinator',
    positionAr: 'منسق عمليات',
    department: 'Operations',
    departmentAr: 'العمليات',
    managerId: 'emp-018',
    managerName: 'Majed Khalid Al-Juhani',
    managerNameAr: 'ماجد خالد الجهني',
    joinDate: '2022-03-20',
    employmentStatus: 'active',
    location: 'Dammam',
    locationAr: 'الدمام',
  },
  {
    id: 'emp-021',
    employeeNumber: 'EMP-2024-0021',
    name: 'Rayan Fahad Al-Rashidi',
    nameAr: 'ريان فهد الرشيدي',
    email: 'r.alrashidi@company.com',
    phone: '+966 50 123 4567',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rayan',
    position: 'Logistics Specialist',
    positionAr: 'أخصائي لوجستيات',
    department: 'Operations',
    departmentAr: 'العمليات',
    managerId: 'emp-018',
    managerName: 'Majed Khalid Al-Juhani',
    managerNameAr: 'ماجد خالد الجهني',
    joinDate: '2022-08-01',
    employmentStatus: 'active',
    location: 'Jeddah',
    locationAr: 'جدة',
  },
  {
    id: 'emp-022',
    employeeNumber: 'EMP-2024-0022',
    name: 'Nayef Ali Al-Zahrani',
    nameAr: 'نايف علي الزهراني',
    email: 'n.alzahrani@company.com',
    phone: '+966 50 234 5678',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nayef',
    position: 'Quality Assurance Officer',
    positionAr: 'مسؤول ضمان جودة',
    department: 'Operations',
    departmentAr: 'العمليات',
    managerId: 'emp-018',
    managerName: 'Majed Khalid Al-Juhani',
    managerNameAr: 'ماجد خالد الجهني',
    joinDate: '2023-01-15',
    employmentStatus: 'active',
    location: 'Riyadh',
    locationAr: 'الرياض',
  },
  {
    id: 'emp-023',
    employeeNumber: 'EMP-2024-0023',
    name: 'Abdulaziz Salem Al-Otaibi',
    nameAr: 'عبدالعزيز سالم العتيبي',
    email: 'a.alotaibi@company.com',
    phone: '+966 50 345 6789',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Abdulaziz',
    position: 'Procurement Officer',
    positionAr: 'مسؤول مشتريات',
    department: 'Operations',
    departmentAr: 'العمليات',
    managerId: 'emp-018',
    managerName: 'Majed Khalid Al-Juhani',
    managerNameAr: 'ماجد خالد الجهني',
    joinDate: '2023-05-01',
    employmentStatus: 'active',
    location: 'Riyadh',
    locationAr: 'الرياض',
  },

  // Sales & Marketing Department
  {
    id: 'emp-024',
    employeeNumber: 'EMP-2024-0024',
    name: 'Sultan Mohammed Al-Ghamdi',
    nameAr: 'سلطان محمد الغامدي',
    email: 's.alghamdi@company.com',
    phone: '+966 50 456 7890',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sultan',
    position: 'Sales Manager',
    positionAr: 'مدير مبيعات',
    department: 'Sales & Marketing',
    departmentAr: 'المبيعات والتسويق',
    joinDate: '2020-09-01',
    employmentStatus: 'active',
    location: 'Riyadh',
    locationAr: 'الرياض',
  },
  {
    id: 'emp-025',
    employeeNumber: 'EMP-2024-0025',
    name: 'Basel Ahmed Al-Harbi',
    nameAr: 'باسل أحمد الحربي',
    email: 'b.alharbi@company.com',
    phone: '+966 50 567 8901',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Basel',
    position: 'Senior Sales Executive',
    positionAr: 'تنفيذي مبيعات أول',
    department: 'Sales & Marketing',
    departmentAr: 'المبيعات والتسويق',
    managerId: 'emp-024',
    managerName: 'Sultan Mohammed Al-Ghamdi',
    managerNameAr: 'سلطان محمد الغامدي',
    joinDate: '2021-06-15',
    employmentStatus: 'active',
    location: 'Jeddah',
    locationAr: 'جدة',
  },
  {
    id: 'emp-026',
    employeeNumber: 'EMP-2024-0026',
    name: 'Dina Khalid Al-Malki',
    nameAr: 'دينا خالد المالكي',
    email: 'd.almalki@company.com',
    phone: '+966 50 678 9012',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Dina',
    position: 'Marketing Specialist',
    positionAr: 'أخصائية تسويق',
    department: 'Sales & Marketing',
    departmentAr: 'المبيعات والتسويق',
    managerId: 'emp-024',
    managerName: 'Sultan Mohammed Al-Ghamdi',
    managerNameAr: 'سلطان محمد الغامدي',
    joinDate: '2022-02-01',
    employmentStatus: 'active',
    location: 'Riyadh',
    locationAr: 'الرياض',
  },
  {
    id: 'emp-027',
    employeeNumber: 'EMP-2024-0027',
    name: 'Raed Hassan Al-Shahrani',
    nameAr: 'رائد حسن الشهراني',
    email: 'r.alshahrani@company.com',
    phone: '+966 50 789 0123',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Raed',
    position: 'Sales Representative',
    positionAr: 'مندوب مبيعات',
    department: 'Sales & Marketing',
    departmentAr: 'المبيعات والتسويق',
    managerId: 'emp-024',
    managerName: 'Sultan Mohammed Al-Ghamdi',
    managerNameAr: 'سلطان محمد الغامدي',
    joinDate: '2022-10-01',
    employmentStatus: 'active',
    location: 'Dammam',
    locationAr: 'الدمام',
  },
  {
    id: 'emp-028',
    employeeNumber: 'EMP-2024-0028',
    name: 'Jana Abdullah Al-Dosari',
    nameAr: 'جنى عبدالله الدوسري',
    email: 'j.aldosari@company.com',
    phone: '+966 50 890 1234',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jana',
    position: 'Digital Marketing Coordinator',
    positionAr: 'منسقة تسويق رقمي',
    department: 'Sales & Marketing',
    departmentAr: 'المبيعات والتسويق',
    managerId: 'emp-024',
    managerName: 'Sultan Mohammed Al-Ghamdi',
    managerNameAr: 'سلطان محمد الغامدي',
    joinDate: '2023-04-10',
    employmentStatus: 'active',
    location: 'Riyadh',
    locationAr: 'الرياض',
  },

  // Legal Department
  {
    id: 'emp-029',
    employeeNumber: 'EMP-2024-0029',
    name: 'Mansour Nasser Al-Otaibi',
    nameAr: 'منصور ناصر العتيبي',
    email: 'm.alotaibi@company.com',
    phone: '+966 50 901 2345',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mansour',
    position: 'Legal Counsel',
    positionAr: 'مستشار قانوني',
    department: 'Legal',
    departmentAr: 'الشؤون القانونية',
    joinDate: '2021-02-01',
    employmentStatus: 'active',
    location: 'Riyadh',
    locationAr: 'الرياض',
  },
  {
    id: 'emp-030',
    employeeNumber: 'EMP-2024-0030',
    name: 'Amal Fahad Al-Shammari',
    nameAr: 'آمال فهد الشمري',
    email: 'a.alshammari@company.com',
    phone: '+966 50 012 3456',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Amal',
    position: 'Legal Assistant',
    positionAr: 'مساعدة قانونية',
    department: 'Legal',
    departmentAr: 'الشؤون القانونية',
    managerId: 'emp-029',
    managerName: 'Mansour Nasser Al-Otaibi',
    managerNameAr: 'منصور ناصر العتيبي',
    joinDate: '2022-07-01',
    employmentStatus: 'active',
    location: 'Riyadh',
    locationAr: 'الرياض',
  },
];

// Helper functions
export function getEmployees(filters?: {
  search?: string;
  department?: string;
  status?: string;
}): Employee[] {
  let filtered = [...mockEmployees];

  if (filters?.search) {
    const searchLower = filters.search.toLowerCase();
    filtered = filtered.filter(
      (emp) =>
        emp.name.toLowerCase().includes(searchLower) ||
        emp.nameAr.includes(filters.search!) ||
        emp.email.toLowerCase().includes(searchLower) ||
        emp.department.toLowerCase().includes(searchLower) ||
        emp.departmentAr.includes(filters.search!) ||
        emp.position.toLowerCase().includes(searchLower) ||
        emp.positionAr.includes(filters.search!)
    );
  }

  if (filters?.department && filters.department !== 'all') {
    filtered = filtered.filter((emp) => emp.department === filters.department);
  }

  if (filters?.status && filters.status !== 'all') {
    filtered = filtered.filter((emp) => emp.employmentStatus === filters.status);
  }

  return filtered;
}

export function getEmployeeById(id: string): Employee | undefined {
  return mockEmployees.find((emp) => emp.id === id);
}

export function getDepartments(): Department[] {
  return departments;
}
